transformation:
  input: C:\Users\tscho\OneDrive - Scientific Network South Tyrol\Projekte\Alpine Space - RESPOnD - 04_Deliverables&Outputs\WP 3\OLE_Content\Climate & Environment\Climate\original_files
  output: C:\Users\tscho\OneDrive - Scientific Network South Tyrol\Projekte\Alpine Space - RESPOnD - 04_Deliverables&Outputs\WP 3\OLE_Content\Climate & Environment\Climate\transformed_files
  file_pattern: "*.tif"
  region_mask: "data/europe.shp"